### PR TITLE
allow both `require(...)` and `import x from ...`

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by tomchentw** [comment]
Sorry, I want to keep it in exporting ES2015 module format only. I don't care about compatibility from `require()` calls because they could still access it.

**Comment by graingert** [comment]
What about only supporting:

```
import x from '...'
```

And
```
const x = require('...');
```

By only including

**Comment by tomchentw** [comment]
No. I don't want to use `add-module-exports`. ES2015 module please. No more `module.exports` stuff.

The named export is there so anyone can do something like this:

```js
var {UnusedFilesWebpackPlugin} = require('unused-files-webpack-plugin');
```

Thanks for the react preset commit, I'll cherrt pick them

**Comment by graingert** [comment]
Why would anyone do that? It's not documented and it's not as common as
require(...).default

**Comment by tomchentw** [comment]
Well, it's my choice to only support ES2015 module. I don't see any good benefits on supporting `module.exports` at all.

**Comment by graingert** [comment]
Of course, I'm just talking about the double export

```
var {UnusedFilesWebpackPlugin} = require('unused-files-webpack-plugin');
```

**Comment by tomchentw** [comment]
Shall I add it to the documentation?

**Comment by tomchentw** [comment]
Released [v2.0.4](https://github.com/tomchentw/unused-files-webpack-plugin/releases/tag/v2.0.4)

**Pull request closed without merging**
