### PR TITLE
Don't use deprecated API in webpack4

### LINKED ISSUE #22: Deprecation warning with webpack 4
Using`webpack 4.1.1`, I get this warning during webpack build:

`
(node:40693) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
`

With help of https://github.com/webpack/webpack/issues/6568#issuecomment-373679018, I was able to trace the culprit to being the `unused-files-webpack-plugin`:

`
    at UnusedFilesWebpackPlugin.apply (/Users/tz-mac/Repos/pex-client/node_modules/unused-files-webpack-plugin/lib/index__8.0.0__.js:105:14)
    at webpack (/Users/tz-mac/Repos/pex-client/node_modules/webpack/lib/webpack.js:37:12)
`

which refers to this line: https://github.com/tomchentw/unused-files-webpack-plugin/blob/e63a89caa2c4564134e56ee2c57cc435cd76363a/lib/index__8.0.0__.js#L105

### PR DESCRIPTION
**Pull request by jquense**
fixes #22 

Sorry did this in the GH editor!

### CODE REVIEW

**Comment by jankanty** [comment]
Hey. These errors looks like they are not working properly in ci: `This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.` Can you look at it and consider accepting this PR?

**Comment by anthonyhastings** [comment]
Changes look correct to me; I'm looking forward to getting this deprecation warning out of my console!

**Comment by kylecesmat** [comment]
@jquense @JanKanty @stipsan is there anything blocking this from being merged/released? It's a minor warning, but would be nice to have it removed from output :)

**Comment by stipsan** [comment]
The ci error should be fixable by running `npm test — -u` and pushing the updated snapshots. Although it looks like the same error is happening in master, ot doesn't look like thos PR broke any test 🤔

**Pull request closed without merging**
