### PR TITLE
if bail is set, callback with error Fixes #10

### LINKED ISSUE #10: with fail `failOnUnused: true` running webpack with --bail does not bail with unused files
I expect webpack to bail if there are any errors from this plugin.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by tomchentw** [comment]
Released [v2.0.5](https://github.com/tomchentw/unused-files-webpack-plugin/releases/tag/v2.0.5)

**Comment by hzoo** [comment]
I think this was a breaking change since webpack wasn't providing any errors without bail: true and when using this plugin + failOnUnused it wouldn't build. Without an error or any message you would have to find out which plugin was updated.

**Comment by tomchentw** [comment]
@hzoo you're right. I'll fix this. Thanks for reporting!

**Comment by tomchentw** [comment]
Released [v3.0.0](https://github.com/tomchentw/unused-files-webpack-plugin/releases/tag/v3.0.0) and deprecated v2.0.5

**Pull request merged**
